//! Text → [`Config`].
//!
//! The parser is deliberately conservative: a line is only turned into a
//! modeled [`Line::Preamp`] / [`Line::Filter`] when we can reproduce it
//! faithfully. Anything else — including filter variants we don't yet support
//! (e.g. `LS 6dB`) — falls through to [`Line::Raw`] and is preserved verbatim.
//!
//! `Channel:` is stateful in APO: it scopes every following command until the
//! next `Channel:`. We track that state and attach the active [`Channel`] to
//! each preamp/filter, consuming the directive itself (it's regenerated on
//! serialize).

use super::model::{Channel, Config, Filter, FilterKind, Line};

/// Parse a full APO configuration (or preset file) from text.
pub fn parse(input: &str) -> Config {
    let mut lines = Vec::new();
    let mut channel = Channel::Both;

    for raw in input.lines() {
        let trimmed = raw.trim();

        if let Some(rest) = strip_prefix_ci(trimmed, "Channel:") {
            channel = parse_channel(rest);
            continue; // consumed — regenerated by the serializer
        }

        if let Some(rest) = strip_prefix_ci(trimmed, "Preamp:")
            && let Some(gain) = parse_preamp(rest)
        {
            lines.push(Line::Preamp {
                gain,
                channel: channel.clone(),
            });
            continue;
        }

        if let Some(filter) = try_parse_filter(trimmed, &channel) {
            lines.push(Line::Filter(filter));
            continue;
        }

        // Preserve the original line, whitespace and all.
        lines.push(Line::Raw(raw.to_string()));
    }

    Config { lines }
}

/// Strip a case-insensitive prefix, returning the remainder if it matched.
fn strip_prefix_ci<'a>(line: &'a str, prefix: &str) -> Option<&'a str> {
    if line.len() >= prefix.len() && line[..prefix.len()].eq_ignore_ascii_case(prefix) {
        Some(&line[prefix.len()..])
    } else {
        None
    }
}

/// Interpret a `Channel:` spec. Stereo `L` / `R` / `L R` are modeled; anything
/// else is kept verbatim as [`Channel::Other`].
fn parse_channel(rest: &str) -> Channel {
    let spec = rest.trim();
    let upper: Vec<String> = spec
        .split_whitespace()
        .map(|t| t.to_ascii_uppercase())
        .collect();
    let refs: Vec<&str> = upper.iter().map(String::as_str).collect();
    match refs.as_slice() {
        ["L"] => Channel::Left,
        ["R"] => Channel::Right,
        ["L", "R"] | ["R", "L"] => Channel::Both,
        _ => Channel::Other(spec.to_string()),
    }
}

/// Parse the body of a `Preamp:` line: `<number> [dB]`.
fn parse_preamp(rest: &str) -> Option<f64> {
    let mut tokens = rest.split_whitespace();
    let value: f64 = tokens.next()?.parse().ok()?;
    match tokens.next() {
        None => Some(value),
        Some(unit) if unit.eq_ignore_ascii_case("dB") && tokens.next().is_none() => Some(value),
        _ => None,
    }
}

/// Try to parse a `Filter:` / `Filter N:` line, attaching the active channel.
fn try_parse_filter(line: &str, channel: &Channel) -> Option<Filter> {
    let (index, body) = strip_filter_prefix(line)?;
    let mut filter = parse_filter_body(index, body)?;
    filter.channel = channel.clone();
    Some(filter)
}

/// Split `Filter:` or `Filter 7:` into its optional index and the remaining body.
fn strip_filter_prefix(line: &str) -> Option<(Option<u32>, &str)> {
    // "Filter" is 6 ASCII bytes; case-insensitive match keeps the slice valid.
    if line.len() < 6 || !line[..6].eq_ignore_ascii_case("Filter") {
        return None;
    }
    let after = line[6..].trim_start();
    let colon = after.find(':')?;
    let label = after[..colon].trim();
    let index = if label.is_empty() {
        None
    } else {
        Some(label.parse::<u32>().ok()?)
    };
    Some((index, &after[colon + 1..]))
}

fn parse_filter_body(index: Option<u32>, body: &str) -> Option<Filter> {
    let mut tokens = body.split_whitespace().peekable();

    let enabled = match tokens.next()?.to_ascii_uppercase().as_str() {
        "ON" => true,
        "OFF" => false,
        _ => return None,
    };

    let kind = FilterKind::from_token(tokens.next()?)?;

    let mut freq = None;
    let mut gain = None;
    let mut q = None;

    while let Some(token) = tokens.next() {
        match token.to_ascii_uppercase().as_str() {
            "FC" => {
                freq = Some(tokens.next()?.parse().ok()?);
                consume_unit(&mut tokens, "Hz");
            }
            "GAIN" => {
                gain = Some(tokens.next()?.parse().ok()?);
                consume_unit(&mut tokens, "dB");
            }
            "Q" => {
                q = Some(tokens.next()?.parse().ok()?);
            }
            // An unrecognised token means we can't faithfully model this line;
            // bail so the caller keeps it as Raw instead of silently dropping it.
            _ => return None,
        }
    }

    Some(Filter {
        enabled,
        kind,
        freq: freq?,
        gain,
        q,
        index,
        channel: Channel::Both,
    })
}

/// Consume an optional unit token (e.g. `Hz`, `dB`) if it's next.
fn consume_unit<'a, I>(tokens: &mut std::iter::Peekable<I>, unit: &str)
where
    I: Iterator<Item = &'a str>,
{
    if tokens.peek().is_some_and(|t| t.eq_ignore_ascii_case(unit)) {
        tokens.next();
    }
}
